### ISSUE TITLE
Punctuation and case sensitive 

### ISSUE THREAD

**Issue by sarapapi** [apptek/SubER#5]
Hi @patrick-wilken,
I am here again to point out some observations I made on the SubER outcomes I obtained from the analysis of different models.
I know that you found no significative differences in the correlation of SubER with and without punctuation and true casing, as reported in the paper, but I think it would be very useful to add an option to the SubER tool in which you can indicate whether to use or not punctuation and true casing. Currently, you are normalizing the text, and tokenization is not needed to compute TER (as far as I understood from your implementation) but it would become necessary if we avoid the normalization step (as they do in the sacrebleu tool).
I noticed that computing SubER by normalizing the text strongly favors systems that are not good at inserting punctuation and correctly capitalizing words and the outcomes of SubER are in fact in contrast with BLEU scores but also with Sigma scores.
Just to give you an idea, I found that a system scoring 5 BLEU point less than all the other systems that I tested can achieve a lower (thus, better) SubER and the difference in the quality of the translation also emerges upon manual evaluation and the absence of punctuation strongly affects the understanding. Therefore, I suggest integrating the option that I mentioned before and maybe further exploring this aspect. 

Thanks

**Comment by patrick-wilken** [comment]
Ok, that all makes sense. :) I implemented it, see #6. Maybe you want to check the details.
Another question is whether we should also change the "TER" metrics to be tokenized and case-sensitive. But I would rather keep it just an interface to sacrebleu with default options. Because it's not really the focus of this repo to provide all the options for the other metrics. But it's easy to set them in `suber/metrics/sacrebleu_interface.py` if someone needs them.

**Comment by sarapapi** [comment]
Hi Patrick, sorry for my late reply but I have taken some time to take a look at the implementation and compute the metrics by myself. The cased version seems sound to me and the results are now consistent with that of the other metrics that I am using. Thanks again for your time.

**Comment by patrick-wilken** [comment]
That sounds good! I will merge then.
